name: Release

on:
  workflow_dispatch:

#  push:
#    paths:
#      - package.json
#    branches:
#      - main
      
jobs:

  build-and-publish:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    environment: 'prod'

    steps:
      - uses: actions/checkout@v4

      - uses: kozmoai/actions-release-ui-components@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          NEBULA_UI_ACTIONS_RW_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          NEBULA_OSS_ACTIONS_RW_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
  